INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(1, 0, 'Abarth', 'Abarth', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(2, 0, 'Alfa Romeo', 'Alfa Romeo', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(3, 0, 'Alpine', 'Alpine', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(4, 0, 'Aston Martin', 'Aston Martin', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(5, 0, 'Audi', 'Audi', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(6, 0, 'Bentley', 'Bentley', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(7, 0, 'BMW', 'BMW', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(8, 0, 'Bollore', 'Bollore', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(9, 0, 'BRP', 'BRP', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(10 0, 'Bugatti', 'Bugatti', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(11, 0, 'Cadillac', 'Cadillac', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(12, 0, 'Caterham', 'Caterham', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(13, 0, 'Chevrolet', 'Chevrolet', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(14, 0, 'Chrysler', 'Chrysler', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(15, 0, 'Citroën', 'Citroën', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(16, 0, 'Cupra', 'Cupra', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(17, 0, 'Dacia', 'Dacia', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(18, 0, 'Daihatsu', 'Daihatsu', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(19, 0, 'DeVinci', 'DeVinci', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(20, 0, 'Dodge', 'Dodge', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(21, 0, 'DS', 'DS', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(22, 0, 'Ferrari', 'Ferrari', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(23, 0, 'Fiat', 'Fiat', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(24, 0, 'Fisker', 'Fisker', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(25, 0, 'Ford', 'Ford', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(26, 0, 'GMC', 'GMC', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(27, 0, 'Gordon Murray Automotive', 'Gordon Murray Automotive', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(28, 0, 'Honda', 'Honda', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(29, 0, 'Hummer', 'Hummer', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(30 0, 'Hyundai', 'Hyundai', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(31, 0, 'Infiniti', 'Infiniti', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(32 0, 'Isuzu', 'Isuzu', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(33, 0, 'Jaguar', 'Jaguar', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(34, 0, 'Jannarelly', 'Jannarelly', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(35, 0, 'Jeep', 'Jeep', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(36, 0, 'Kia', 'Kia', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(37, 0, 'Koenigsegg', 'Koenigsegg', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(38, 0, 'Lamborghini', 'Lamborghini', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(39, 0, 'Lancia', 'Lancia', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(40, 0, 'Land-Rover', 'Land-Rover', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(41, 0, 'Lexus', 'Lexus', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(42, 0, 'Lotus', 'Lotus', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(43, 0, 'Maserati', 'Maserati', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(44, 0, 'Maybach', 'Maybach', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(45, 0, 'Mazda', 'Mazda', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(46, 0, 'Mclaren', 'Mclaren', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(47, 0, 'Mercedes', 'Mercedes', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(48, 0, 'MG Motor', 'MG Motor', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(49, 0, 'Mini', 'Mini', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(50, 0, 'Mitsubishi', 'Mitsubishi', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(51, 0, 'Nissan', 'Nissan', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(52, 0, 'Opel', 'Opel', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(53, 0, 'Pagani', 'Pagani', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(54, 0, 'Peugeot', 'Peugeot', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(55, 0, 'Pgo', 'Pgo', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(56, 0, 'Polestar', 'Polestar', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(57, 0, 'Porsche', 'Porsche', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(58, 0, 'Renault', 'Renault', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(59, 0, 'Rolls Royce', 'Rolls Royce', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(60, 0, 'Saab', 'Saab', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(61, 0, 'Seat', 'Seat', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(62, 0, 'Shelby', 'Shelby', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(63, 0, 'Skoda', 'Skoda', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(64, 0, 'Smart', 'Smart', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(65, 0, 'Ssangyong', 'Ssangyong', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(66, 0, 'Subaru', 'Subaru', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(67, 0, 'Suzuki', 'Suzuki', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(68, 0, 'Tesla', 'Tesla', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(69, 0, 'Toyota', 'Toyota', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(70, 0, 'Venturi', 'Venturi', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(71, 0, 'Volkswagen', 'Volkswagen', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(72, 0, 'Volvo', 'Volvo', '', 1);
INSERT INTO `llx_c_car_brands` (`rowid`, `entity`, `ref`, `label`, `description`, `active`) VALUES(73, 0, 'Zenvo', 'Zenvo', '', 1);



